language: bash
services:
  - docker

before_script:
  - ./docker/buildsteps/login.sh
  - source ./docker/buildsteps/common.sh

script:
  - ./docker/buildsteps/build.sh
  - ./docker/buildsteps/deploy.sh

after_script:
  - ./docker/buildsteps/clean.sh
